name: 'Flake8 Jupyter Notebook'
description: 'Does PEP8 validation for your python Jupyter Notebooks'
inputs:
  debug:
    required: false
    description: Dump debug information
    default: false
runs:
  using: 'docker'
  image: 'docker://mhitza/flake8-jupyter-notebook-github-action:latest'
