name: Build & Publish Image

on:
  release:
    types: [ created ]

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: login to Docker Hub
      run: |
        docker login -u mhitza -p "${{ secrets.DOCKER_HUB_TOKEN }}"

    - name: setup TAG_NAME
      run: |
        export TAG_NAME=${{ github.event.release.tag_name }}
        echo "::set-env name=TAG_NAME::$TAG_NAME"

    - name: Build
      run:
        docker build . --file Dockerfile --tag mhitza/flake8-jupyter-notebook-github-action:${{ env.TAG_NAME }}

    - name: Publish
      run: docker push mhitza/flake8-jupyter-notebook-github-action:${{ env.TAG_NAME }}
