name: Build & Publish Image

on:
  push:
    branches: [ master ]
    paths: 
      - Dockerfile
      - annotate
      - entrypoint.sh
  release:
    types: [ created ]

jobs:
  docker-hub-login:
    runs-on: ubuntu-latest
    steps:
      - name: login to Docker Hub
        run: |
          docker login -u mhitza -p "${{ secrets.DOCKER_HUB_TOKEN }}"
          
  latest-image:
    if: ${{ github.event_name }} === 'push' 
    runs-on: ubuntu-latest
    needs: [ docker-hub-login ]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag mhitza/flake8-jupyter-notebook-github-action:latest
    - name: Publish
      run: docker push mhitza/flake8-jupyter-notebook-github-action:latest
